version: "3.9"
services:
  # MySQL
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_USER: "${DB_USER}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - kemahin

  adminer:
    image: adminer
    restart: always
    ports:
      - "9191:8080"

  app:
    container_name: api_kemahin
    build: .
    restart: "no"
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app

volumes:
  database_mysql:
  api:

networks:
  pinjem:
    driver: bridge
