// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Helper is an autogenerated mock type for the Helper type
type Helper struct {
	mock.Mock
}

// HashAndSalt provides a mock function with given fields: pwd
func (_m *Helper) HashAndSalt(pwd []byte) string {
	ret := _m.Called(pwd)

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(pwd)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ValidateHash provides a mock function with given fields: secret, hash
func (_m *Helper) ValidateHash(secret string, hash string) bool {
	ret := _m.Called(secret, hash)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(secret, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
