name: on-push-master
on:
  pull_request:
    branches:
      - 'main'
      - 'master'
  push: 
    branches:
      - 'main'
      - 'master'

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    container: golang:1.17
    services:
        mysql:
          image: mariadb:10.1
          env:
            MYSQL_ROOT_PASSWORD: password
          ports:
            - 3307:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: running unit test
      run: | 
        echo "${{ secrets.ENV }}" > ./app/config/config.json
        go mod tidy
        go test ./... -cover